# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.csi-driver-spec.aws-csi-role}}
  name: {{ .Values.component}}-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.csi-driver-spec.aws-account}}:role/{{ .Values.csi-driver-spec.aws-csi-role}}
