apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.component}}-ingressrule
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: {{ .Values.ports.frontend}}
      - path: /api/catalogue/
        pathType: Prefix
        backend:
          service:
            name: catalogue-service
            port:
              number: {{ .Values.ports.catalogue}}
      - path: /api/user/
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: {{ .Values.ports.user}}
      - path: /api/cart/
        pathType: Prefix
        backend:
          service:
            name: cart-service
            port:
              number: {{ .Values.ports.cart}}
      - path: /api/shipping/
        pathType: Prefix
        backend:
          service:
            name: shipping-service
            port:
              number: {{ .Values.ports.shipping}}
      - path: /api/payment/
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: {{ .Values.ports.payment}}
      