apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component}}-service
spec:
  selector:
    pods: {{ .Values.component}}-pods
  ports:
    - protocol: TCP
      port: {{ .Values.global.ports.user}}
      targetPort: {{ .Values.port}}
      