component: catalogue

image: vnsharsha7999/catalogue:v1


MinCpu: 200m  # Minimum CPU cores in millicores
MaxCpu: 500m  # Maximum CPU cores in millicores
maxUtilization: 90  # Maximum CPU usage limit

minReplicas: 1
maxReplicas: 10

